"""add students table

Revision ID: 1dc3e7a1548a
Revises: 742e3318cb11
Create Date: 2024-07-01 15:50:50.016914

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dc3e7a1548a"
down_revision: Union[str, None] = "742e3318cb11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("firstname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lastname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("degree_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student")
    # ### end Alembic commands ###
