"""add foreign key from student to assessment

Revision ID: 24b9a5ade6a3
Revises: 1ada632294fd
Create Date: 2024-07-12 11:52:21.556642

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24b9a5ade6a3"
down_revision: Union[str, None] = "1ada632294fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student", sa.Column("assessment_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_student_assessment_id"), "student", ["assessment_id"], unique=False
    )
    op.create_foreign_key(
        "student_assessment_id_fkey", "student", "assessment", ["assessment_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("student_assessment_id_fkey", "student", type_="foreignkey")
    op.drop_index(op.f("ix_student_assessment_id"), table_name="student")
    op.drop_column("student", "assessment_id")
    # ### end Alembic commands ###
