"""add new internal_credentials table

Revision ID: 2f240785d0e2
Revises: 24b9a5ade6a3
Create Date: 2024-07-12 12:03:08.386271

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f240785d0e2"
down_revision: Union[str, None] = "24b9a5ade6a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internal_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id", "username"),
    )
    op.create_index(
        op.f("ix_internal_credentials_assessment_id"),
        "internal_credentials",
        ["assessment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_internal_credentials_assessment_id"), table_name="internal_credentials"
    )
    op.drop_table("internal_credentials")
    # ### end Alembic commands ###
