"""add assessment_id column to mark table

Revision ID: 71f5d28220b5
Revises: b4ac26635c45
Create Date: 2024-08-20 15:06:49.990916

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "71f5d28220b5"
down_revision: Union[str, None] = "b4ac26635c45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mark", sa.Column("assessment_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_mark_assessment_id"), "mark", ["assessment_id"], unique=False
    )
    op.create_foreign_key(None, "mark", "assessment", ["assessment_id"], ["id"])

    bind = op.get_bind()
    bind.execute(
        text(
            "UPDATE mark SET assessment_id = (SELECT assessment.id FROM assessment WHERE assessment.code = mark.exam_id)"
        )
    )

    op.alter_column("mark", "assessment_id", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mark_assessment_id_fkey", "mark", type_="foreignkey")
    op.drop_index(op.f("ix_mark_assessment_id"), table_name="mark")
    op.drop_column("mark", "assessment_id")
    # ### end Alembic commands ###
