"""Add mark model

Revision ID: 742e3318cb11
Revises: 5080d4533395
Create Date: 2024-06-13 10:56:54.518406

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "742e3318cb11"
down_revision: Union[str, None] = "5080d4533395"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question", sa.Integer(), nullable=False),
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("section", sa.Integer(), nullable=False),
        sa.Column("mark", sa.Float(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("marker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mark_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mark_id", sa.Integer(), nullable=False),
        sa.Column("mark", sa.Float(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("marker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mark_id"],
            ["mark.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mark_history")
    op.drop_table("mark")
    # ### end Alembic commands ###
