"""add index on exam_id to tables

Revision ID: 905a24c008fc
Revises: 1dc3e7a1548a
Create Date: 2024-07-10 11:36:34.548170

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "905a24c008fc"
down_revision: Union[str, None] = "1dc3e7a1548a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_answer_exam_id"), "answer", ["exam_id"], unique=False)
    op.create_index(op.f("ix_mark_exam_id"), "mark", ["exam_id"], unique=False)
    op.create_index(op.f("ix_student_exam_id"), "student", ["exam_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_exam_id"), table_name="student")
    op.drop_index(op.f("ix_mark_exam_id"), table_name="mark")
    op.drop_index(op.f("ix_answer_exam_id"), table_name="answer")
    # ### end Alembic commands ###
