"""add fk from answer and mark to student

Revision ID: a6d3be52d408
Revises: a43ab9fdd90e
Create Date: 2024-07-10 11:45:47.219213

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6d3be52d408"
down_revision: Union[str, None] = "a43ab9fdd90e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "answer", "student", ["username"], ["username"])
    op.create_foreign_key(None, "mark", "student", ["username"], ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mark_username_fkey", "mark", type_="foreignkey")
    op.drop_constraint("answer_username_fkey", "answer", type_="foreignkey")
    # ### end Alembic commands ###
