"""Change exam_id and ip fields in answer

Revision ID: e11049a10795
Revises: 11f1bdccc186
Create Date: 2024-06-11 15:01:07.101510

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e11049a10795"
down_revision: Union[str, None] = "11f1bdccc186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "exam_id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "answer",
        "ip",
        existing_type=sa.VARCHAR(),
        type_=postgresql.INET(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "ip",
        existing_type=postgresql.INET(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "answer",
        "exam_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
